global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 15s
  repeat_interval: 1m
  receiver: 'telegram-receiver'

  routes:
    - receiver: 'telegram-receiver'
      match:
        severity: 'critical'

receivers:
  - name: 'telegram-receiver'
    telegram_configs:
      - api_url: 'https://api.telegram.org'
        bot_token: 'YOUR_BOT_TOKEN'
        chat_id: 'YOUR_CHAT_ID'
        parse_mode: ''
